name: CDCI for AWS

on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [18.x]


    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: 'Create env file'
        run: |
           echo "${{ secrets.ENV_FILE_PRD }}" > .env
           cat .env
      - run: npm run test:e2e
      - run: npm run build
      # - run: |
      #     mv package-lock.json package.json .env dist/ 
      #     cd dist
      #     npm install --production
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /var/www/my-app/
          remote_host: 3.93.56.43
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
           


