name: CDCI for AWS

on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: 'Create env file'
        run: |
          echo "${{ API_ENV_PRD.ENV_FILE_PRD }}" > .env
          cat .env
      - run: npm run build
      - run: npm run test:e2e


      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/my-app/
          remote_host: ec2-3-93-56-43.compute-1.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ API_ENV_PRD.SSH_PRIVATE_KEY }}"

